[package]
name = "http_server"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
tokio = { version = "1.44.0", features = ["full"] }

[lib]
name = "http"
path = "src/lib/mod.rs"

[[bin]]
name = "http_server"
path = "src/main.rs"

[dev-dependencies]
reqwest = "0.12.12"
